import * as ctx from  '../../../../quasar.conf.js'

import palosDefaultSettings from '../../../../src/store/data/palosDefaultSettings'

describe('Home page', () => {
  beforeEach(() => {
    window.localStorage.clear()
    cy.visit('/')
    cy.get('#closePrivacyDialogBtn')
      .click()
    cy.get('#playBtn')
      .should('contain', 'play_arrow')
    cy.get('#appMain')
      .should('be.visible')
  })
  it('has proper page title', () => {
    cy.title()
      .should('include', 'A Compás')
  })
  it('can play using default settings', () => {
    cy.get('#playBtn')
      .should('contain', 'play_arrow')
      .click()
    cy.get('#playBtn')
      .should('contain', 'stop')
      .click()
  })
  it('can play each palo', () => {
    palosDefaultSettings.forEach(function(palo) {
      cy.get('#paloBtn')
        .click()
      cy.get('#palosDialog')
        .should('be.visible')
        .should('contain', palo.label)
      cy.get('#palosDialog .q-radio__label')
        .each(($elt, index, $labels) => {
          if ($elt.html() === palo.label) {
            cy.wrap($elt)
              .click()
            cy.get('#playBtn')
              .should('contain', 'play_arrow')
              .click()
            cy.get('#playBtn')
              .should('contain', 'stop')
              .click()
          }
        })
    })
    cy.get('#paloBtn')
      .click()
    cy.get('#palosDialog')
      .should('be.visible')
    cy.get('#closePalosDialogBtn')
      .click()
    cy.get('#appMain')
      .should('be.visible')
  })
  it('can display the help popin', () => {
    cy.get('#menuBtn')
      .click()
    cy.get('#sideMenu')
      .should('be.visible')
    cy.get('#helpQItem')
      .click()
    cy.get('#helpDialog')
      .should('be.visible')
      .should('contain', 'Help')
    cy.get('#closeHelpBtn')
      .click()
    cy.get('#appMain')
      .should('be.visible')
  })
  it('can display the tuning fork', () => {
    cy.get('#menuBtn')
      .click()
    cy.get('#sideMenu')
      .should('be.visible')
    cy.get('#tuningForkQItem')
      .click()
    cy.get('#tuningDialog')
      .should('be.visible')
      .should('contain', 'Tuning fork')
    cy.get('#tuningDialog .q-btn')
      .each(($elt, index, $btns) => {
        cy.wrap($elt)
          .click()
      })
    cy.get('#closeTuningDialogBtn')
      .click()
    cy.get('#appMain')
      .should('be.visible')
  })
  it('can display the privacy popin', () => {
    cy.get('#menuBtn')
      .click()
    cy.get('#sideMenu')
      .should('be.visible')
    cy.get('#privacyQItem')
      .click()
    cy.get('#privacyDialog')
      .should('be.visible')
      .should('contain', 'Privacy')
    cy.get('#enableAndClosePrivacyDialogBtn')
      .click()
    cy.get('#appMain')
      .should('be.visible')
    cy.get('#sideMenu')
      .should('be.visible')
    cy.get('#privacyQItem')
      .click()
    cy.get('#privacyDialog')
      .should('be.visible')
    cy.get('#toggleTrackVisits')
      .click()
    cy.get('#closePrivacyDialogBtn')
      .click()
    cy.get('#appMain')
      .should('be.visible')
  })
})
