stages:
  - build

variables:
  NPM: "npm --cache /tmp/npm-cache"

# Jobs

build_web_job:
  script:
    - apt-get -y update
    - apt-get -y dist-upgrade
    - apt-get -y install curl gnupg
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - apt-get install -y nodejs git rsync
    - $NPM install
    - npx quasar build
  stage: build
  tags:
    - development
