stages:
  - test

variables:
  YARN: "yarn --cache-folder /tmp/yarn-cache"
  DEBIAN_FRONTEND: "noninteractive"

# Jobs

text_web_job:
  script:
    - ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
    - apt-get -y -qq update
    - apt-get -y -qq dist-upgrade
    - apt-get -y -qq install curl gnupg
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt-get update
    # Some deps are for Cypress.
    # See https://docs.cypress.io/guides/guides/continuous-integration.html#Advanced-setup
    - apt-get install -y -qq nodejs git make g++ gcc rsync yarn xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
    - npm install -g @quasar/cli
    - npm install -g --unsafe-perm @quasar/icongenie
    - ./icongenie.sh
    - $YARN install
    - npx quasar build
    - $YARN run test:e2e:CI
  stage: test
  tags:
    - development
  image: ubuntu:focal
