# This file is part of A Compás.
#
# A Compás is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# A Compás is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with A Compás. If not, see <http://www.gnu.org/licenses/>.

stages:
  - build

# Jobs

build_web_job:
  script:
    - apt-get -y update
    - apt-get -y dist-upgrade
    - apt-get -y install curl
    - curl -sL https://deb.nodesource.com/setup_9.x | bash -
    - apt-get install -y nodejs git rsync
    - npm install
    - ./prepare.sh
  stage: build
  tags:
    - development
