version: '2'

services:

  app_dev:
    build: .
    command: nginx -c /opt/app/nginx.conf
#    volumes:
#      - .:/opt/app
#      - /opt/app/node_modules
    ports:
      - 8080:8080

  app_production:
    build: .
    command: nginx -c /opt/app/nginx.conf
#    volumes:
#      - .:/opt/app
#      - /opt/app/node_modules
    ports:
      - 8080:8080
    restart: always
